program: wandb_sweep.py
method: bayes  # Bayesian Optimization
metric:
  name: val_loss
  goal: minimize

early_terminate:
  type: hyperband
  min_iter: 5
  max_iter: 30
  s: 2

parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e-2

  fused_dim:
    values: [128, 256]

  hidden_dim:
    values: [64, 128]

  fusion_type:
    values: ["simple", "transformer"]

  mode:
    values: ["both"]

  #contrastive_loss_weight:
  #  distribution: uniform
  #  min: 0.0
  #  max: 1.0

  fusion_agg:
    values: ["cls", "mean", "max"]

  num_heads:
    values: [1, 2, 4, 8]

  num_self_attention_layers:
    values: [1, 2]

  dropout_prob:
    distribution: uniform
    min: 0.1
    max: 0.7

  # Contrastive parameters
  contrastive_loss_type:
    values: ["none"]    # or "sym" or "none" if you wanted
  #supcon_temp:
  #  distribution: uniform
  #  min: 0.03
  #  max: 0.3

  # --- NEW: Data augmentation parameters ---
  #noise_std:
  #  distribution: uniform
  #  min: 0.0
  #  max: 0.03

  #col_drop_prob:
  #  distribution: uniform
  #  min: 0.0
  #  max: 0.1

  #smiles_aug_prob:
  #  distribution: uniform
  #  min: 0.0
  #  max: 1.0
  
  num_views:
    values: [0]

